### ISSUE TITLE
Use wavy line in text underlining

### ISSUE THREAD

**Issue by zenwalker** [steelbrain/linter-ui-default#230]
Dotted borders is ugly for me.
Maybe use the wavy borders line on all others IDE? It looks nice.

<img width="488" alt="screen shot 2017-03-25 at 19 16 45" src="https://cloud.githubusercontent.com/assets/1812128/24324015/acb747fc-118f-11e7-86f2-4de441cb8f0b.png">

Code from my styles.less:

```css
atom-text-editor.editor .linter-highlight.linter-error .region,
.linter-highlight.linter-error .region {
  border-bottom: none;
  background-image:
    linear-gradient(45deg, transparent 65%, #D13B2E 80%, transparent 90%),
    linear-gradient(135deg, transparent 5%, #D13B2E 15%, transparent 25%),
    linear-gradient(135deg, transparent 45%, #D13B2E 55%, transparent 65%),
    linear-gradient(45deg, transparent 25%, #D13B2E 35%, transparent 50%);
  background-size: 8px 2px;
  background-repeat: repeat-x;
  background-position: left bottom;
}

atom-text-editor.editor .linter-highlight.linter-warning .region,
.linter-highlight.linter-warning .region {
  border-bottom: none;
  background-image:
    linear-gradient(45deg, transparent 65%, #AD7C0B 80%, transparent 90%),
    linear-gradient(135deg, transparent 5%, #AD7C0B 15%, transparent 25%),
    linear-gradient(135deg, transparent 45%, #AD7C0B 55%, transparent 65%),
    linear-gradient(45deg, transparent 25%, #AD7C0B 35%, transparent 50%);
  background-size: 8px 2px;
  background-repeat: repeat-x;
  background-position: left bottom;
}
```
