### ISSUE TITLE
How to change the underline type

### ISSUE THREAD

**Issue by ooJerryLeeoo** [steelbrain/linter-ui-default#261]
I use this code to change the underline into a `2px dotted underline`, and it work very well under v1.2.2, but after this package support wavy underline, my `2px dotted underline` become this:
![screen shot 2017-04-16 at 09 33 14](https://cloud.githubusercontent.com/assets/20783502/25068050/64da37cc-2289-11e7-8ba6-837eb76c39cd.png)

@steelbrain  can you help me out? thanks.

UPD: Sorry, I forgot to post the code:

``` less
atom-text-editor.editor .linter-highlight, .linter-highlight {
  .error_type(@color, @priority) {
    .region {
      border-bottom: 2px dotted @color;
    }
    &.linter-gutter {
      color: @color;
      z-index: @priority;
    }
  }
  &.linter-info {
    .error_type(green, -1);
  }
  &.linter-warning {
    .error_type(yellow, 0);
  }
  &.linter-error {
    .error_type(red, 1);
  }
}
.tree-view {
  .error_type(@color) {
    border-bottom: 2px dotted @color;
  }
  .linter-info {
    .error_type(green);
  }
  .linter-warning {
    .error_type(yellow);
  }
  .linter-error {
    .error_type(red);
  }
}
```
