### ISSUE TITLE
Linter panel opens in new tab

### ISSUE THREAD

**Issue by lexicalunit** [steelbrain/linter-ui-default#348]
- `Atom@1.18.0-beta3`
- `linter@2.1.4`
- `linter-ui-default@1.6.1`.

Editor tab with source code that has some linter warnings in it.

![screen shot 2017-06-12 at 9 04 59 am](https://user-images.githubusercontent.com/1903876/27037698-571e6f30-4f4e-11e7-84f8-1cca6bbf1ab8.png)

Then I click on the linter widget in the statusbar and, I get a new tab?

![screen shot 2017-06-12 at 9 05 05 am](https://user-images.githubusercontent.com/1903876/27037720-660049ce-4f4e-11e7-96ba-08b86b2e402d.png)

Clicking on the tab to see what's there I find an empty linter panel:

![screen shot 2017-06-12 at 9 05 09 am](https://user-images.githubusercontent.com/1903876/27037740-728d08b2-4f4e-11e7-9b8f-29ca268ecd14.png)

No errors in console. This also happens with the Atom One Dark and other themes so it's not the UI-Theme that I'm using in the screenshots.

Linter in question is [`linter-eslint`](https://atom.io/packages/linter-eslint) if that matters? Not sure if it does or not.

Possibly relevant Atom config settings:

```
"*":
  core:
    audioBeep: false
    titleBar: "custom"
  editor:
    autoIndentOnPaste: false
    fontFamily: "Inconsolata"
    fontSize: 21
    preferredLineLength: 100
    scrollPastEnd: true
    showInvisibles: true
    softWrapAtPreferredLineLength: true
    tabLength: 4
  linter:
    lintOnChange: true
  "linter-ui-default":
    panelHeight: 200
  "markdown-preview":
    grammars: [
      "source.gfm"
      "source.litcoffee"
      "text.html.basic"
      "text.md"
      "text.plain"
      "text.plain.null-grammar"
      "source.gfm.nvatom"
    ]
    useGitHubStyle: true
  tabs: {}
  "tree-view":
    hideIgnoredNames: true
```

```
± apm --version
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 3.5.1
git 2.9.2

± apm list
Built-in Atom Packages (91)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.4
├── one-light-ui@1.10.4
├── one-dark-syntax@1.7.1
├── one-light-syntax@1.7.1
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.6
├── archive-view@0.63.2
├── autocomplete-atom-api@0.10.1
├── autocomplete-css@0.16.2
├── autocomplete-html@0.8.0
├── autocomplete-plus@2.35.4
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.3
├── background-tips@0.27.0
├── bookmarks@0.44.4
├── bracket-matcher@0.85.5
├── command-palette@0.40.4
├── dalek@0.2.1
├── deprecation-cop@0.56.7
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.4
├── exception-reporting@0.41.4
├── find-and-replace@0.208.3
├── fuzzy-finder@1.5.8
├── github@0.3.3
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.5
├── image-view@0.61.2
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.7.1
├── link@0.31.3
├── markdown-preview@0.159.12
├── metrics@1.2.5
├── notifications@0.67.2
├── open-on-github@1.2.1
├── package-generator@1.1.1
├── settings-view@0.249.4
├── snippets@1.1.4
├── spell-check@0.71.4
├── status-bar@1.8.11
├── styleguide@0.49.6
├── symbols-view@0.116.0
├── tabs@0.106.0
├── timecop@0.36.0
├── tree-view@0.217.1
├── update-package-dependencies@0.12.0
├── welcome@0.36.4
├── whitespace@0.36.2
├── wrap-guide@0.40.2
├── language-c@0.58.0
├── language-clojure@0.22.2
├── language-coffee-script@0.48.7
├── language-csharp@0.14.2
├── language-css@0.42.2
├── language-gfm@0.89.0
├── language-git@0.19.1
├── language-go@0.44.0
├── language-html@0.47.2
├── language-hyperlink@0.16.1
├── language-java@0.27.1
├── language-javascript@0.126.1
├── language-json@0.19.1
├── language-less@0.32.0
├── language-make@0.22.3
├── language-mustache@0.14.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.38.0
├── language-property-list@0.9.1
├── language-python@0.45.2
├── language-ruby@0.71.0
├── language-ruby-on-rails@0.25.2
├── language-sass@0.59.0
├── language-shellscript@0.25.0
├── language-source@0.9.0
├── language-sql@0.25.5
├── language-text@0.7.2
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.35.0
└── language-yaml@0.29.0

Community Packages (60) /Users/me/.atom/packages
├── MagicPython@1.0.10
├── activate-power-mode@2.0.0
├── aesthetic-ui@4.0.0
├── atom-beautify@0.29.26
├── atom-isort@1.3.0
├── atom-language-avro@0.0.13
├── auto-update-packages@1.0.1
├── autocomplete-python@1.8.64
├── base16-syntax@1.8.0
├── busy-signal@1.4.3
├── column-select@0.2.0
├── cursor-indicator@1.2.8
├── event-watch@4.0.2
├── file-icons@2.1.7
├── highlight-selected@0.13.1
├── indent-guide-improved@1.4.12
├── intentions@1.1.2
├── isotope-light-ui@2.2.7
├── language-applescript@0.3.0
├── language-babel@2.65.1
├── language-cmake@0.3.0
├── language-diff@0.7.0
├── language-docker@1.1.8
├── language-rust@0.4.10
├── language-scala@1.1.8
├── line-length-break@0.4.0
├── linter@2.1.4
├── linter-clang@4.1.1
├── linter-coffeelint@1.2.1
├── linter-csslint@1.3.4
├── linter-docker@0.2.0
├── linter-erb@1.1.0
├── linter-eslint@8.2.1
├── linter-flake8@2.2.1
├── linter-js-standard@3.9.1
├── linter-jsonlint@1.3.0
├── linter-rubocop@2.1.1
├── linter-shellcheck@1.4.4
├── linter-tidy@2.3.1
├── linter-ui-default@1.6.1
├── linter-write-good@0.9.0
├── minimap@4.28.2
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-selection@4.4.0
├── multi-wrap-guide@0.28.4
├── native-ui@0.21.0
├── no-title-bar@0.6.6
├── nvatom@0.11.0
├── python-yapf@0.14.0
├── red-wavy-underline@0.3.3
├── set-syntax@0.3.2
├── soft-wrap-indicator@1.0.1
├── sort-lines@0.14.0
├── standard-formatter@2.8.0
├── tab-control@0.6.10
├── tabs-to-spaces@1.0.3
├── toggle-quotes@1.0.1
└── trailing-spaces@0.4.0
```
