### ISSUE TITLE
not showing styling

### ISSUE THREAD

**Issue by andrewbanchich** [steelbrain/linter-ui-default#386]
i'm not sure why, but the styling for the linter ui does not seem to be showing for me anymore. i am on Atom 1.18 and Windows 7.

![capture](https://user-images.githubusercontent.com/13824577/28419821-40f30aec-6d2e-11e7-9b8b-9d99da6e0ada.PNG)

**Comment by Arcanemagus** [comment]
What "styling" isn't showing? That looks normal for the status bar when you have no messages.

If you mean colors, the icons are colored when they have more than 0 messages in that category.

**Comment by andrewbanchich** [comment]
here is how it appears when i create an error

![capture](https://user-images.githubusercontent.com/13824577/28429177-d394b664-6d49-11e7-851b-0807de880bf9.PNG)

isn't it supposed to appear like this?

![official gif](https://cloud.githubusercontent.com/assets/4278113/23879933/1ab17e2a-0872-11e7-803d-3fe0ccfc6790.gif)

**Comment by Arcanemagus** [comment]
It hasn't looked that way since v1.5.0 was released including https://github.com/steelbrain/linter-ui-default/pull/300.

**Comment by andrewbanchich** [comment]
why were those icons/styling removed? seems like a huge step backward in terms of a UI in my opinion.

**Comment by Arcanemagus** [comment]
You'd have to go through the related issues for the reasoning. If I remember it was due to a request that the numbers were indistinguishable for colorblind people.

**Comment by andrewbanchich** [comment]
@steelbrain any way to add the nice UI back while making it accessible to the color blind? or maybe make it a setting you can toggle?

**Comment by steelbrain** [comment]
Not yet unfortunately 😢

**Comment by muppetjones** [comment]
@Arcanemagus That's kind of funny, b/c I'm colorblind, and the other way (pre 1.5) was much much easier for me to see.

**Comment by Arcanemagus** [comment]
I'd suggest trying out `linter-ui-plus` as an alternative... but they are done _almost_ the same way there:

`linter-ui-default`:
![image](https://user-images.githubusercontent.com/427137/28472280-d1d76794-6df4-11e7-9047-ca74d9dc19f4.png)

`linter-ui-plus`:
![image](https://user-images.githubusercontent.com/427137/28472291-db8db900-6df4-11e7-9ae8-2a18e64245e3.png)

**Comment by mehcode** [comment]
@andrewbanchich @muppetjones Is the ui in `linter-ui-plus` an improvement? I strongly feel that the aversion to `linter-ui-default` is not that they are icons but that they are _line_ icons.

**Comment by andrewbanchich** [comment]
@mehcode @steelbrain meh, it's a small improvement. the reason i liked the old linter-ui-default UI was... it was a UI. a UI (to me) implies graphical elements. that's why they're called GUIs. if you remove the graphics and make it just text or small font-like icons, in my opinion it is no longer a UI. if i wanted just text or small symbols i could use the terminal.

**Comment by mehcode** [comment]
@andrewbanchich Honestly, I disagree with you. But let's stop and appreciate that Atom is a hackable editor. 

If you use `linter-ui-plus` you can apply the following in your `styles.less` to get the style you want (you might be able to do something similar with `linter-ui-default` but I haven't checked, this relies on all the information needed to be in the DOM)

![screen shot 2017-07-25 at 8 39 14 am](https://user-images.githubusercontent.com/753919/28580590-c3b43cfa-7114-11e7-935e-ced598beb1a9.png)


```less
@import "ui-variables";

.linter-ui-plus.status-bar {
  // Give each tile a minimum width to appear fixed in 99% of cases
  .tile {
    display: inline-block;
    min-width: 2em;
    padding-left: 0.4em;
    padding-right: 0.4em;
    text-align: center;
    position: relative;
  }

  // When the tile has errors ...
  .tile:not([data-count="0"]) {
    // ... hide the default text
    color: white;

    // ... add a color highlight
    &::after {
      position: absolute;
      top: 0.25em;
      right: 0;
      bottom: 0.25em;
      left: 0;
      z-index: 1;
      display: flex;
      align-items: center;
      font-weight: 500;
      justify-content: center;
      border-radius: @component-border-radius;
      content: attr(data-count);
    }

    &.tile-error::after {
      background-color: @text-color-error;
    }

    &.tile-warning::after {
      background-color: @text-color-warning;
    }

    &.tile-info::after {
      background-color: @text-color-info;
    }
  }

  // Hide the icons
  .tile::before {
    display: none;
  }
}
```
