### ISSUE TITLE
Highlight rendering problem

### ISSUE THREAD

**Issue by neoziro** [steelbrain/linter-ui-default#441]
A rendering problem occurs (see screenshot) with a lot of highlights displayed in editor. It results into scrolling problem and editor freezing.

<img width="517" alt="screen shot 2017-09-17 at 20 16 57" src="https://user-images.githubusercontent.com/266302/30532939-2dd798c6-9c57-11e7-8eae-ca08f5f2bad3.png">

After investigation I found the source of the problem and I fixed it by overcharging stylesheet. The problem is the background-image used to highlight linter-error.

<img width="372" alt="screen shot 2017-09-18 at 09 45 19" src="https://user-images.githubusercontent.com/266302/30532950-33a4f42e-9c57-11e7-8cfe-a57149de9a28.png">

I fixed it like that:

```less
atom-text-editor.editor .linter-highlight.linter-error, .linter-highlight.linter-error {
  background: fadeout(red, 90%);
}

atom-text-editor.editor .linter-highlight.linter-warning, .linter-highlight.linter-warning {
  background: fadeout(orange, 90%);
}
```
