### ISSUE TITLE
[feature request] make tooltip text selectable.

### ISSUE THREAD

**Issue by trusktr** [steelbrain/linter-ui-default#526]
It is super convenient to be able copy text inside a tooltip (f.e. lint messages, type errors, etc).

No matter what I try with `user-select`, I cannot make the text selectable. For example, I have this in my stylesheet:

```less
#linter-tooltip {
	user-select: text;
	* { user-select: text; }
}
```

but it won't work. Me thinks there is an `event.preventDefault()` call somewhere.

I really like that in `atom-ide` when I hover on the gutter icons and reveal the gutter tooltips, I can select the text. It is convenient for searching on Google, or messaging the error to a colleague who may know about it, etc.
