### ISSUE TITLE
Panel doesn't display

### ISSUE THREAD

**Issue by pdxwolfy** [steelbrain/linter-ui-default#547]
For the last several weeks, the linter-ui-default panel has repeatedly stopped working. I typically have it set to show the panel when there is stuff to report, but it doesn't do so. The little circles in the gutter show up fine, but the panel does not. 

I've found that, when this happens, I have to go into linter-ui-default's settings and toggle "Show Panel" on. Once I do that, the panel begins to work. However, the next day -- sometimes later in the same day -- it again stops working and I again have to turn "Show Panel" on. I've been unable to determine what triggers this change -- I've looked at restarting Atom, logging out, rebooting, powering off, and nothing in particular seems to cause the setting to get disabled. 

I am using Atom 1.39.0 under Mac OS 10.14.5 with linter-ui-default 1.7.1

**Comment by alexgvozden** [comment]
same here, tried 5-6 different things mentioned in all posts...

**Comment by pdxwolfy** [comment]
I'm glad I'm not entirely alone. In one experiment, I tried enabling the Show Provider Name just to say if that setting would also revert, but it did not. Only the Show Panel setting gets disabled. I have a detection script running now that checks the config.json file every 10 minutes for the ShowPanel changing, but haven't yet isolated the problem. It seems to only happen when Atom is shut down and restarted, but it's inconsistent.

**Comment by focusaurus** [comment]
Duplicate of https://github.com/steelbrain/linter-ui-default/issues/518 but thanks for adding good debug info here as well. I just placed a $50 bounty for a fix: https://www.bountysource.com/issues/64787205-panel-never-displays

**Comment by steelbrain** [comment]
Didn't know it was an actual bug (just thought it was a misconfig because Panel never shows itself when there's no errors).

The bug bounty won't be necessary, I'll try to investigate today

**Comment by steelbrain** [comment]
*facepalm*. My hunch was right. I am unable to repro this with a bunch of tested providers, on default config.

Please note that when (if) the default bottom dock is hidden, it won't seem like there's anything there, so you have to hover the bottom middle to find it out

Before hovering:
<img width="1632" alt="Screenshot 2019-08-11 at 1 57 02 AM" src="https://user-images.githubusercontent.com/4278113/62826783-66e49880-bbdb-11e9-9a75-b14280dbe0bf.png">

After hovering:
<img width="1636" alt="Screenshot 2019-08-11 at 1 57 28 AM" src="https://user-images.githubusercontent.com/4278113/62826784-6946f280-bbdb-11e9-8be2-c5a11e21babe.png">

Also do a `cat ~/.atom/config.*` in your terminal and have a look at linter/linter-ui-defeault config to see what you have set up, posting it here would help with debugging

**Comment by pdxwolfy** [comment]
Posting my config.cson below:

The problem here is that I have "Hide Panel When Empty" and "Show Panel" set, as well as "Hide Panel Unless Editor". Everything works fine. The panel comes, the panel goes as expected. Then, at some point, the panel stops working, and when I go back to settings, "Show Panel" is no longer set. When I set "Show Panel", it again starts working until the next time it stops working.

I have a feeling that the this may be tied to `linter-markdown`.

```yml
"*":
  "advanced-open-file":
    createDirectories: true
    fuzzyMatch: true
    helmDirSwitch: true
    ignoredPatterns: [
      "*.pyc"
      "*.pyo"
      ".DS_Store"
      "*.o"
      "*.min.js"
      "*.min.css"
      ".tags"
      "*.psd"
      "*.png"
      "*.ico"
      "*.gif"
      "*.jpg"
      "*.jpeg"
    ]
  "atom-beautify":
    general:
      beautifyEntireFileOnSave: false
    js:
      brace_style: "collapse-preserve-inline"
      end_of_line: "LF"
      end_with_comma: true
      end_with_newline: true
      jslint_happy: true
      max_preserve_newlines: 2
      object_curly_spacing: true
  "atom-ctags":
    autoBuildTagsWhenActive: true
  "atom-meld": {}
  "atom-package-deps":
    ignored: []
  "atom-runner": {}
  "atom-trello":
    devKey: "5cb7117158723636955e52192daf83e3"
    token: "dce42f8b9ff3facabc6f35b39b41d82a712290608f4b6d53d15c823a65ff86b9"
  "auto-close-html2":
    insertWhitespaceOnClose: false
  "auto-detect-indentation":
    showSpacingInStatusBar: false
  "autoclose-html":
    additionalGrammars: [
      "*"
    ]
    forceBlock: [
      "style"
      "body"
      "head"
      "html"
      "p"
      "blockquote"
      "ul"
      "ol"
      "dl"
      "table"
      "tr"
      "thead"
      "tbody"
      "tfoot"
      "nav"
      "section"
      "main"
      "article"
      "aside"
      "div"
    ]
    forceInline: [
      "h1"
      "h2"
      "h3"
      "h4"
      "h5"
      "h6"
      "li"
      "option"
      "td"
      "th"
      "dd"
      "dt"
    ]
  "autocomplete-ctags":
    caseInsensitive: false
  "autocomplete-plus":
    autoActivationDelay: 500
    backspaceTriggersAutocomplete: true
    confirmCompletion: "tab"
    enableExtendedUnicodeSupport: true
    fileBlacklist: [
      "*.none"
    ]
    maxVisibleSuggestions: 20
    minimumWordLength: 1
    scopeBlacklist: [
      "none.none"
    ]
    useAlternateScoring: false
  "autohide-tree-view":
    hideDelay: 0
    minWidth: 50
    pushEditor: true
    showDelay: 0
    touchAreaSize: 0
    triggerAreaSize: 200
  "block-comment-plus":
    wrapWith: "New lines"
  "bracket-matcher":
    highlightMatchingLineNumber: true
  "color-picker":
    automaticReplace: true
    randomColor: false
    uppercaseColorValues: true
  "color-tabs":
    markerStyle: "round"
  core:
    allowPendingPaneItems: false
    disabledPackages: [
      "about"
      "autosave"
      "background-tips"
      "metrics"
      "welcome"
      "wrap-guide"
      "archive-view"
      "tree-view-open-files"
      "tree-view-git-branch"
      "linter-tidy"
      "less-than-slash"
      "deprecation-cop"
      "markdown-preview"
      "link"
      "fuzzy-finder"
      "language-clojure"
      "language-csharp"
      "language-go"
      "language-java"
      "language-objective-c"
      "language-php"
      "language-todo"
      "language-toml"
      "language-gfm"
      "autoflow"
      "github"
      "language-git"
      "git-diff"
      "open-on-github"
      "linter-json-lint"
      "timecop"
    ]
    ignoredNames: [
      "*.a"
      "*.bak"
      "*.class"
      "*.db"
      "*.dds"
      "*.dll"
      "*.dylib"
      "*.eot"
      "*.exe"
      "*.gif"
      "*.ico"
      "*.idb"
      "*.jar"
      "*.jpeg"
      "*.jpg"
      "*.lib"
      "*.ncb"
      "*.o"
      "*.obj"
      "*.pdb"
      "*.pdf"
      "*.png"
      "*.psd"
      "*.pyc"
      "*.pyo"
      "*.sdf"
      "*.so"
      "*.sublime-workspace"
      "*.suo"
      "*.swf"
      "*.tga"
      "*.ttf"
      "*.zip"
      "*~"
      ".DS_Store"
      ".git"
      ".bundle"
      "build"
      ".sass-cache"
      ".cache"
      ".DS_Store"
      ".env"
    ]
    openEmptyEditorOnStart: false
    packagesWithKeymapsDisabled: [
      "emmet"
      "restart-atom"
      "atom-meld"
      "markdown-preview-plus"
      "magic-reflow"
      "node-debugger"
      "atom-overtype-mode"
      "atom-sync"
      "print-code"
      "quick-resize"
      "csslint"
      "goto"
      "script-runner"
      "script"
    ]
    projectHome: "/Users/wolfy/Atom"
    reopenProjectMenuCount: 30
    telemetryConsent: "no"
    themes: [
      "wolfy-dark-ui"
      "wolfy-dark-syntax"
    ]
    titleBar: "custom"
    useProxySettingsWhenCallingApm: false
    useTreeSitterParsers: false
    warnOnLargeFileLimit: 1
  csslint:
    hideOnNoErrors: true
  docblockr:
    c_style_block_comments: true
    extend_double_slash: false
    param_description: false
    return_description: false
    simple_mode: true
  "double-tag":
    allowEndTagSync: true
    ignoredTags: [
      "area"
      "base"
      "br"
      "col"
      "command"
      "embed"
      "hr"
      "img"
      "input"
      "keygen"
      "link"
      "menuitem"
      "meta"
      "param"
      "source"
      "track"
      "wbr"
    ]
  editor:
    atomicSoftTabs: false
    fontFamily: "Fira Code"
    fontSize: 16
    invisibles: {}
    lineHeight: 1.25
    maxScreenLineLength: 1999
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    scrollSensitivity: 80
    showInvisibles: true
    softWrapHangingIndent: 4
  "exception-reporting":
    userId: "a28b11f0-81d8-dfbf-81ca-3e5a8a610cd5"
  "file-icons":
    strategies:
      modelines: false
  "file-types":
    $caseSensitive: true
    "*.mason.html$": "text.html.mason"
    md: "source.gfm"
  "find-and-replace":
    autocompleteSearches: false
    focusEditorAfterSearch: true
    liveSearchMinimumCharacters: 1
    projectSearchResultsPaneSplitDirection: "right"
    scrollToResultOnLiveSearch: true
    searchContextLineCountAfter: 1
  "fuzzy-finder": {}
  "git-diff":
    showIconsInEditorGutter: true
  "git-diff-details":
    enableSyntaxHighlighting: true
  "git-plus":
    general:
      _analyticsUserId: "d00952bd-1a54-419d-8cc3-d57cf24a9ebf"
      enableStatusBarIcon: false
    remoteInteractions:
      pullBeforePush: true
  "hey-pane":
    expandedWidth: 60
  "hide-tree":
    focus: false
  "highlight-column":
    opacity: 0.025
  "highlight-selected":
    highlightBackground: true
    highlightInPanes: false
    onlyHighlightWholeWords: false
    showInStatusBar: false
  "language-babel":
    autoIndentJSX: true
  "less-than-slash": {}
  "line-count-status":
    format: "[%s]"
  linter:
    lintOnChange: false
    lintOnOpen: false
  "linter-csslint": {}
  "linter-erb":
    erbExecutablePath: "erubis"
    rubyExecutablePath: "/usr/local/rbenv/shims/ruby"
  "linter-eslint":
    advanced:
      disableFSCache: true
      eslintRulesDirs: [
        "/Users/wolfy"
      ]
    disabling:
      disableWhenNoEslintConfig: false
    global:
      eslintrcPath: "/Users/wolfy/.eslintrc.yml"
      globalNodePath: "/Users/wolfy/.npm-global"
    lintHtmlFiles: true
  "linter-htmlhint":
    disableWhenNoHtmlhintConfig: false
  "linter-js-standard":
    checkStyleDevDependencies: true
    lintHtmlFiles: true
    lintMarkdownFiles: true
    showEslintRules: true
    style: "semistandard"
  "linter-jshint":
    executablePath: "/Users/wolfy/.npm-global/bin/jshint"
    jshintFileName: "/Users/wolfy/.jshintrc"
    lintInlineJavaScript: true
  "linter-jslint":
    jslintFileName: "/Users/wolfy/.jslintrc"
    jslintVersion: "es6"
    lintInlineJavaScript: true
  "linter-json-lint":
    allowComments: true
  "linter-less": {}
  "linter-markdown":
    presetStyleGuideWithoutConfig: true
  "linter-perl":
    additionalPerlOptions: "-T"
    lintOptions: "all,no-undefined-subs,no-dollar-underscore"
  "linter-perl-check-syntax":
    executablePath: "/usr/local/bin/perl5"
    incPathsAbsolute: [
      "/usr/local/lib/perl5 /Users/wolfy/devserv"
    ]
    tainted: true
    warnings: true
  "linter-perlcritic":
    executablePath: "/usr/local/bin/perlcritic"
  "linter-rails-best-practices": {}
  "linter-remark": {}
  "linter-rubocop":
    command: "/Users/wolfy/bin/rubocop"
    ignoredExtensions: [
      "erb"
      "html.erb"
      "md"
      ".erb"
      ".html.erb"
      ".md"
    ]
  "linter-ruby":
    ignoredExtensions: [
      "erb"
      "html.erb"
      "md"
      ".erb"
      ".html.erb"
      ".md"
    ]
    rubyExecutablePath: "/usr/local/bin/ruby"
  "linter-ruby-reek":
    executablePath: "/usr/local/rbenv/shims/reek"
  "linter-sass-lint":
    configFile: "/Users/wolfy/.sass-lint.yml"
  "linter-spell":
    personalDictionaryPath: "/Users/wolfy/etc/spell.txt"
  "linter-stylelint":
    disableWhenNoConfig: false
    showIgnored: true
    useStandard: true
  "linter-tidy":
    tidyExecutablePath: "/usr/local/bin/tidy"
  "linter-ui-default":
    alwaysTakeMinimumSpace: true
    decorateOnTreeView: "Files and Directories"
    hidePanelUnlessTextEditor: true
    panelHeight: 250
    showPanel: true
    showStatusBar: false
    showTooltip: false
    statusBarClickBehavior: "Jump to next issue"
    statusBarRepresents: "Current File"
    tooltipFollows: "Mouse"
    useBusySignal: false
  "linter-write-good":
    additionalArgs: "--no-tooWordy --no-weasel --no-thereIs --no-passive --no-adverb"
  lipsum:
    htmlExtensions: [
      ".xxxhtml"
      ".xxxhtm"
      ".xxxphp"
      ".xxxtwig"
      ".xxxtpl"
    ]
    maxPerParagraph: 10
    maxPerSentence: 12
    minPerParagraph: 2
    minPerSentence: 4
    paragraphs: 3
  livereload:
    applyImageLive: true
    exts: "html, css, js, png, gif, jpg, php, php5, py, rb, erb, coffee, jsx"
  "local-history": {}
  "markdown-preview":
    liveUpdate: false
  "markdown-preview-plus":
    markdownItConfig:
      useLazyHeaders: false
    previewConfig:
      liveUpdate: false
    syncConfig:
      syncEditorOnPreviewScroll: true
      syncPreviewOnEditorScroll: true
    useGitHubStyle: true
  "merge-conflicts":
    gitPath: "/opt/local/bin/git"
  minimap:
    displayPluginsControls: false
    plugins:
      bookmarks: true
      bookmarksDecorationsZIndex: 0
      cursorline: true
      cursorlineDecorationsZIndex: 0
      "minimap-autohide": true
      "minimap-autohideDecorationsZIndex": 0
  "multi-wrap-guide":
    autoSaveChanges: false
    columns: [
      80
      100
    ]
    rows: [
      80
    ]
    silent: true
  "node-debugger":
    nodePath: "/usr/local/bin/node"
  "omni-ruler":
    columns: [
      "16"
      "32"
      "48"
      "64"
      "80"
    ]
    customRulerColor: "#493b3c"
    useCustomRulerColor: true
  "one-dark-ui": {}
  "open-in-browsers":
    BrowserPlus: false
    IE: false
    LocalHost: false
    Opera: false
  "platformio-ide-terminal":
    ansiColors:
      normal:
        blue: "#000ce3"
      zBright:
        brightBlue: "#00c0ff"
    core:
      scrollback: 2500
    iconColors:
      blue: "#00b6fc"
      orange: "#f09c13"
    style: {}
    toggles:
      autoClose: true
      selectToCopy: false
  "prettier-atom":
    formatOnSaveOptions:
      enabled: true
      isDisabledIfNotInPackageJson: true
      showInStatusBar: true
  "quick-resize":
    sizeOne:
      height: 800
      width: 1024
    sizeTwo:
      description: "New size with save"
      height: 800
      width: 1640
  "remote-edit": {}
  "remote-sync":
    logToConsole: true
  "ruby-block":
    highlightLineNumber: true
  "ruby-block-converter":
    maxLines: 5
  "ruby-test": {}
  script:
    escapeConsoleOutput: false
    stopOnRerun: true
  "script-runner":
    scrollbackDistance: 1000
  "seeing-is-believing": {}
  "shebang-set-grammar":
    aliases: "{\"bash\": \"shell\", \"sh\": \"shell\", \"perl5\": \"perl\"}"
  "spell-check":
    addKnownWords: true
    grammars: [
      "source.asciidoc"
      "source.gfm"
      "text.git-commit"
      "text.md"
      "text.plain"
      "text.plain.null-grammar"
    ]
    knownWords: [
      "attr_reader"
      "backreference"
      "backreferences"
      "backtick"
      "backticks"
      "blockquote"
      "clearfix"
      "codepen"
      "doctypes"
      "ecmascript"
      "endhighlight"
      "es5"
      "es6"
      "fieldset"
      "figcaption"
      "flexbox"
      "flexboxes"
      "gigapixels"
      "img"
      "javascript"
      "jpgs"
      "js"
      "lipsum"
      "livescript"
      "lossiness"
      "pdxwolfy"
      "rubocop"
      "rubular"
      "scriptular"
      "textarea"
      "destructuring"
    ]
  "split-diff":
    colors:
      addedColor: "#5ea280"
      overrideThemeColors: true
      removedColor: "#bf6060"
    ignoreWhitespace: true
  "status-bar":
    cursorPositionFormat: "%L:%C"
    selectionCountFormat: "{%L:%C}"
  "sublime-block-comment":
    pad: true
  "tab-control":
    autoSaveChanges: true
  "tab-smart-sort":
    ordering: "dir, base, ext"
  tabs:
    enableVcsColoring: true
  "terminal-plus":
    core: {}
    style:
      theme: "grass"
    toggles:
      autoClose: true
  "tidy-markdown":
    ensureFirstHeaderIsH1: false
  "toggle-quotes":
    quoteCharacters: "\"'`"
  "tree-view":
    alwaysOpenExisting: true
    autoReveal: true
    hideVcsIgnoredFiles: true
  "tree-view-autoresize":
    animationMilliseconds: 0
    delayMilliseconds: 0
    maximumWidth: 300
    padding: 10
  "tree-view-git-branch":
    location: "inside"
    separator: true
  "tree-view-git-status":
    gitFlow:
      enabled: false
  "tree-view-open-files":
    maxHeight: 500
  "w3c-validation":
    cssReportType: "all"
    validateOnSave: false
  welcome:
    showOnStartup: false
  whitespace:
    ignoreWhitespaceOnCurrentLine: false
    keepMarkdownLineBreakWhitespace: false
".attribute-values.js.jsx.source":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 2
".bash":
  editor:
    softTabs: true
    tabLength: 2
".basic.html.text":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    preferredLineLength: 80
    softTabs: true
    softWrapHangingIndent: 2
    tabLength: 2
  "multi-wrap-guide":
    columns: [
      80
      120
    ]
".c.source":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softTabs: false
    softWrap: false
    softWrapAtPreferredLineLength: false
    softWrapHangingIndent: 4
    tabLength: 4
".coffee.source":
  editor:
    preferredLineLength: 80
    softTabs: true
    tabLength: 2
  "multi-wrap-guide":
    columns: [
      80
      100
    ]
".cpp.source":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softTabs: false
    softWrap: false
    softWrapAtPreferredLineLength: false
    softWrapHangingIndent: 4
    tabLength: 4
".css.less.source":
  editor:
    preferredLineLength: 80
    softTabs: true
    tabLength: 2
  "multi-wrap-guide":
    columns: [
      80
      100
    ]
".css.scss.source":
  editor:
    nonWordCharacters: "/\\()\"':,.;<>~!#%^&*|+=[]{}`?…"
    showIndentGuide: true
    softWrapHangingIndent: 2
    tabType: "soft"
".css.source":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softTabs: true
    softWrapHangingIndent: 2
    tabLength: 2
".css.source.styled":
  editor:
    softWrapHangingIndent: 2
".diff.source":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 2
".erb.html.text":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 2
    tabLength: 2
    tabType: "soft"
".gemfile.ruby.source":
  editor:
    softWrapHangingIndent: 2
".gfm.source":
  editor:
    preferredLineLength: 80
    softTabs: true
    tabLength: 2
  "multi-wrap-guide":
    columns: [
      80
      100
    ]
".git-commit.text":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 4
".git-config.source":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 4
".git-rebase.text":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 4
".html.mason.text":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    preferredLineLength: 80
    softTabs: true
    softWrapHangingIndent: 2
    tabLength: 2
  "multi-wrap-guide":
    columns: [
      80
      100
    ]
".html.ruby.text":
  editor:
    showIndentGuide: true
    softWrapHangingIndent: 2
    tabType: "soft"
".html.tcl.text":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 4
".hyperlink.text":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 2
    tabLength: 2
".js.jsx.react.source":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 2
".js.jsx.source":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 2
".js.rails.source source.jquery.js":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 2
".js.regexp.replacement.source":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 4
".js.regexp.source":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 4
".js.source":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softTabs: true
    softWrapHangingIndent: 2
    tabLength: 2
".js.source.subtlegradient":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 2
".json.source":
  editor:
    softTabs: true
    tabLength: 2
".md.text":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    showIndentGuide: false
    softTabs: true
    softWrap: true
    tabLength: 2
  "multi-wrap-guide":
    columns: [
      80
    ]
".null-grammar.plain.text":
  editor:
    preferredLineLength: 80
    softTabs: true
    tabLength: 2
  "multi-wrap-guide":
    columns: [
      80
      120
    ]
".perl.source":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    preferredLineLength: 80
    softTabs: true
    softWrapHangingIndent: 4
    tabLength: 2
  "multi-wrap-guide":
    columns: [
      80
      100
    ]
".perl6.source":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 4
".plain.text":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    preferredLineLength: 80
    softTabs: true
    softWrap: true
    softWrapAtPreferredLineLength: true
    softWrapHangingIndent: 0
    tabLength: 8
  "multi-wrap-guide":
    columns: [
      80
      120
    ]
".plist.text.xml":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 4
".rails.rjs.ruby.source":
  editor:
    softWrapHangingIndent: 2
".rails.ruby.source":
  editor:
    softWrapHangingIndent: 2
".ruby.source":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    preferredLineLength: 80
    softTabs: true
    softWrapHangingIndent: 2
    tabLength: 2
    tabType: "soft"
  "multi-wrap-guide":
    columns: [
      80
      100
    ]
".ruby.source.sql":
  editor:
    softWrapHangingIndent: 2
".sass.source":
  editor:
    autoIndentOnPaste: true
    nonWordCharacters: "/\\()\"':,.;<>~!#%^&*|+=[]{}`?…"
    showIndentGuide: true
    softWrapHangingIndent: 2
    tabType: "soft"
".sassdoc.source":
  editor:
    showIndentGuide: true
    softWrapHangingIndent: 2
    tabType: "soft"
".shell-session.text":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 4
".shell.source":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    preferredLineLength: 80
    softTabs: true
    softWrapHangingIndent: 4
    tabLength: 2
  "multi-wrap-guide":
    columns: [
      80
      100
    ]
".source.tcl":
  editor:
    nonWordCharacters: "/\\()\"':,.<>~!@#$%^&*|+=[]{}`?-_"
    softWrapHangingIndent: 4
".source.yaml":
  editor:
    softTabs: true
    tabLength: 2
```
